const advancedLesson07=document.querySelector('#advanced-lesson');
function syncAdvancedTarget07(){if(advancedLesson07)advancedLesson07.open=location.hash==='#advanced-lesson'||/^#s(?:0[1-9]|1[0-9]|2[0-4])$/.test(location.hash)}
addEventListener('hashchange',syncAdvancedTarget07);syncAdvancedTarget07();
const decodeTransitions={start:{'12':.34,unlimited:.20,'10':.22,several:.15,many:.09},'12':{days:.62,paid:.18,'.':.12,hours:.08},'10':{days:.58,paid:.20,'.':.14,hours:.08},several:{days:.70,'.':.30},many:{days:.65,'.':.35},unlimited:{'.':.55,leave:.25,days:.20},days:{'.':.55,per:.25,of:.12,annually:.08},paid:{days:.60,leave:.40},leave:{'.':.70,annually:.30},per:{year:.80,month:.20},of:{leave:1},annually:{'.':1},year:{'.':1},month:{'.':1}};
function pickGreedy(dist){return Object.entries(dist).sort((a,b)=>b[1]-a[1])[0][0]}
function sampleFrom(entries,probs){const u=Math.random();let cumulative=0;for(let i=0;i<entries.length;i+=1){cumulative+=probs[i];if(u<cumulative)return entries[i][0]}return entries.at(-1)[0]}
function pickTemperature(dist,temperature){const entries=Object.entries(dist);const scaled=entries.map(([,p])=>Math.log(p)/temperature);const m=Math.max(...scaled);const exps=scaled.map(v=>Math.exp(v-m));const total=exps.reduce((a,b)=>a+b,0);const probs=exps.map(v=>v/total);return sampleFrom(entries,probs)}
function pickTopK(dist,k){const entries=Object.entries(dist).sort((a,b)=>b[1]-a[1]).slice(0,k);const total=entries.reduce((sum,[,p])=>sum+p,0);const probs=entries.map(([,p])=>p/total);return sampleFrom(entries,probs)}
function runDecoding(strategy){const tokens=[];let node='start';for(let step=0;step<8;step+=1){const dist=decodeTransitions[node];if(!dist)break;let token;if(strategy==='greedy')token=pickGreedy(dist);else if(strategy==='temperature')token=pickTemperature(dist,1.6);else token=pickTopK(dist,2);tokens.push(token);if(token==='.')break;node=token}return tokens}
function renderDecoding(strategy){const tokens=runDecoding(strategy);let sentence='The leave policy allows';tokens.forEach(token=>{sentence+=token==='.'?'.':' '+token});const trace=tokens.map((token,index)=>`<div>Step ${index+1}: picked <code>${token}</code></div>`).join('');const output=document.querySelector('#decodeOutput');if(output)output.innerHTML=`${trace}<p><b>${sentence}</b></p><p class="fine-print">${tokens.length} generated tokens · ${strategy} decoding</p>`}
const decodeButtons=[...document.querySelectorAll('.decode-strategy-button')];
function selectDecodeStrategy(button){decodeButtons.forEach(item=>{const active=item===button;item.classList.toggle('active',active);item.classList.toggle('secondary',!active);item.setAttribute('aria-pressed',String(active))});renderDecoding(button.dataset.strategy)}
decodeButtons.forEach(button=>button.addEventListener('click',()=>selectDecodeStrategy(button)));if(decodeButtons[0])selectDecodeStrategy(decodeButtons[0]);
